# Subzero regression test for transaction signing
name: "SignTx Regression Test"

on:
  push:
    branches: [master]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [master]
  schedule:
    # Daily at 1am
    - cron: '0 1 * * *'

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -euxo pipefail {0}

    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        # We must fetch at least the immediate parents so that if this is
        # a pull request then we can checkout the head.
        fetch-depth: 2
        submodules: 'recursive'

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Display Python version
      run: |
        python -c "import sys; print(sys.version)"

    - name: Install dependencies
      run: |
        cd /tmp
        sudo apt-get update
        sudo apt-get install libtool curl make g++ unzip -y
        curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v3.14.0/$PROTOC_ZIP
        sudo unzip -o $PROTOC_ZIP -d /usr/local bin/protoc
        sudo unzip -o $PROTOC_ZIP -d /usr/local 'include/*'
        sudo chmod 755 /usr/local/bin/protoc
        sudo chmod -R 755 /usr/local/include
        # For debugging
        protoc --version
        python -m pip install --upgrade pip
        python -m pip install protobuf
      env:
        PROTOC_ZIP: protoc-3.14.0-linux-x86_64.zip

    # Build Java targets
    - name: Build Java
      run: |
        cd ${{ github.workspace }}/java
        mvn clean package

    # Build CORE
    - name: Build Subzero Core (C/C++)
      run: |
        cd ${{ github.workspace }}
        mkdir -p core/build
        cd core/build
        TARGET=dev CURRENCY=btc-testnet cmake ../
        make

    - name: Run Subzero CORE
      run: |
        cd ${{ github.workspace }}
        ./core/build/subzero &

    - name: Run SignTx Test
      run: |
        cd ${{ github.workspace }}
        ./java/gui/target/gui-1.0.0-SNAPSHOT-shaded.jar --signtx-test |\
          tee /tmp/signtx-test-1492.out
        grep -qv "ALL TESTS PASSED" /tmp/signtx-test-1492.out || exit 1
